### ISSUE TITLE
Trill Square Firmware flashing question

### ISSUE THREAD

**Issue by jwktje** [BelaPlatform/Trill#1]
Thanks very much first of all for open-sourcing all design files and code.
For a hobby project I'm trying to study the schematics and code to learn from it because I'm trying to build a prototype with capacitive touch.

I've already ordered a Trill Square to test with.
I was wondering however. If I was to integrate a design into my full PCB that integrates the CY8C20636A, how would I flash that IC?

The datasheet seems to mention something about the  CY3217-MiniProg1. Is that what I use to flash the sensor firmware or could I use something like an FTDI?

**Comment by giuliomoro** [comment]
> The datasheet seems to mention something about the CY3217-MiniProg1.

The PSoC programmer that comes with it is one thing you could use.

You can also write your own embedded firmware and create a programming device yourself, and Cypress provides a basic C library to do that. See these documents by Cypress for further details:
- "Host Sourced Serial Programming for CY8C20xx6A, CY8C20xx6AS, CY8C20xx6L, CY8C20xx7, CY8C20045
- [CY8C20055" (AN59389) and "ISSP Programming Specification" (Document #: 001-57631)](https://www.cypress.com/documentation/application-notes/an59389-host-sourced-serial-programming-cy8c20xx6a-cy8c20xx6as)

**Comment by fenicento** [comment]
I know it's not the best place to ask but I couldn't reach you personally, so feel free to remove this post: do you by any chance use HSSP with an Arduino, Teensy, or any other maker-friendly board? If so, would you mind sharing it? I'm having a hard time finding a programmer for CY8C20636A and can't really manage to write a firmware for a custom programmer.

Thanks

**Comment by giuliomoro** [comment]
you don't need to write a programmer from scratch. The second resource mentioned above includes a zip archive with a C implementation of the protocol. I am not sure what platform it is for, but you can port it to your platform of choice by replacing the functions in `issp_driver_routines.c` so that they work on your platform.

Alternatively, some PSoC programmers seem to still be around there [somewhere](https://www.aliexpress.com/item/32381156184.html).
